[package]
name = "substrate-engine"
version = "0.1.0"
authors = ["ajzaff <ajzaff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "stack"
path = "src/lib/stack.rs"

[dependencies]
rand = "0.8.3"
num = "0.3"
num-derive = "0.3"
num-traits = "0.2"